name: Make WebAssembly
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        wasi_sdk_version: [19, 20]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Downloading wasi-sdk
      run: |
        cd ${{github.workspace}}
        wget --no-verbose https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${{matrix.wasi_sdk_version}}/wasi-sdk-${{matrix.wasi_sdk_version}}.0-linux.tar.gz
        tar xf wasi-sdk-${{matrix.wasi_sdk_version}}.0-linux.tar.gz

    - name: Downloading binaryen
      run: |
        cd ${{github.workspace}}
        wget --no-verbose https://github.com/WebAssembly/binaryen/releases/download/version_112/binaryen-version_112-x86_64-linux.tar.gz
        tar xf binaryen-version_112-x86_64-linux.tar.gz

    - name: make
      run: make -j$(nproc) WASI_SDK="${{github.workspace}}/wasi-sdk-${{matrix.wasi_sdk_version}}.0/" WASM_OPT="${{github.workspace}}/binaryen-version_112/bin/wasm-opt"

